### PR TITLE
fix: prevent crash when invalid OpenAPI spec is loaded for tool servers

### LINKED ISSUE #20207: issue: Infinite loading screen when MCP tool is enabled.
### Check Existing Issues

- [x] I have searched for any existing and/or related issues.
- [x] I have searched for any existing and/or related discussions.
- [x] I have also searched in the CLOSED issues AND CLOSED discussions and found no related items (your issue might already be addressed on the development branch!).
- [x] I am using the latest version of Open WebUI.

### Installation Method

Docker

### Open WebUI Version

0.6.42, 0.6.43

### Ollama Version (if applicable)

N/A

### Operating System

N/A

### Browser (if applicable)

N/A

### Confirmation

- [x] I have read and followed all instructions in `README.md`.
- [x] I am using the latest version of **both** Open WebUI and Ollama.
- [x] I have included the browser console logs.
- [x] I have included the Docker container logs.
- [x] I have **provided every relevant configuration, setting, and environment variable used in my setup.**
- [x] I have clearly **listed every relevant configuration, custom setting, environment variable, and command-line option that influences my setup** (such as Docker Compose overrides, .env values, browser settings, authentication configurations, etc).
- [x] I have documented **step-by-step reproduction instructions that are precise, sequential, and leave nothing to interpretation**. My steps:
- Start with the initial platform/version/OS and dependencies used,
- Specify exact install/launch/configure commands,
- List URLs visited, user input (incl. example values/emails/passwords if needed),
- Describe all options and toggles enabled or changed,
- Include any files or environmental changes,
- Identify the expected and actual result at each stage,
- Ensure any reasonably skilled user can follow and hit the same issue.

### Expected Behavior

Opening the URL, frontend should load.

### Actual Behavior

Only sidebar loads, loading animation stays in place, error in browser console:

### Steps to Reproduce

Log in to Open WebUI, create an External Tool connection, like this:

Image

Save it, enable it.

--->  Frontend still works at this point flawlessly! 

Hit Ctrl-F5 in browser, frontend stuck in loading state, with error on console:

Image

Use Settings to disable the External tool:

Image

Hit Ctrl-F5 again - frontend works correctly again.

### Logs & Screenshots

**Open WebUI JS error when External tool MCP definition active:**

```
Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Object.entries (<anonymous>)
    at d1 (index.ts:1253:39)
    at index.ts:388:15
    at Array.map (<anonymous>)
    at Ss (index.ts:349:6)
    at Q (+layout.svelte:119:31)
    at +layout.svelte:159:37
    at te (+layout.svelte:105:10)
    at async Promise.all (:3000/index 3)
    at async +layout.svelte:154:9

```

Frontend in permanent loading state:

Image

### Additional Information

Tested in 0.6.42 and 0.6.43 too.

Frontend does work if the External tools are not enabled when the browser starts the session, and stuff breaks with a Ctrl-F5.

### PR DESCRIPTION
**Pull request by Classic298**
Description:
Adds defensive checks to prevent the frontend from crashing when an invalid or non-OpenAPI spec is configured for External Tool connections.
Changes:
- Guard against undefined paths in convertOpenApiToToolPayload to prevent Object.entries crash
- Detect MCP-style configs used for OpenAPI connections and return a helpful error message instead of breaking the UI
This fixes the infinite loading screen that occurred when users accidentally configured an MCP server using the OpenAPI connection type.
Fixes #20207

### Contributor License Agreement

By submitting this pull request, I confirm that I have read and fully agree to the [Contributor License Agreement (CLA)](https://github.com/open-webui/open-webui/blob/main/CONTRIBUTOR_LICENSE_AGREEMENT), and I am providing my contributions under its terms.

> [!NOTE]
> Deleting the CLA section will lead to immediate closure of your PR and it will not be merged in.

### CODE REVIEW

File: src/lib/apis/index.ts [hunk 1]
```diff
@@ -379,6 +379,14 @@ export const getToolServersData = async (servers: object[]) => {
 					}
 
 					if (res) {
+						// Detect MCP-style configs that were incorrectly used for OpenAPI tool servers
+						if (res.mcpServers && !res.paths) {
```
Comment (tjbck) [inline src/lib/apis/index.ts]: should just do res.paths, and say invalid openapi spec

**Review by tjbck — CHANGES_REQUESTED** [review]

**Comment by Classic298** [comment]
@tjbck addressed

**Comment by tjbck** [comment]
Thanks!
